version: '2'
services:
  wordpress:
    image: minusetcortex/apsb:devel
    ports:
      - 80:80
      - 443:443
    environment:
      ADMIN_EMAIL: florianchazal@gmail.com
      THEMES: pinboard
      DB_HOST: ${APSB_DB_HOST}
      DB_NAME: ${APSB_DB_NAME}
      DB_USER: ${APSB_DB_USER}
      DB_PASS: ${APSB_DB_PASSWORD}
      PROD_FTP_HOST: ${EX2_FTP_HOST}
      PROD_FTP_USER: ${EX2_FTP_USER}
      PROD_FTP_PASSWORD: ${EX2_FTP_PASSWORD}
      PLUGINS: >-
        akismet,
        contact-form-7,
        login-form-recaptcha,
        ml-slider,
        really-simple-captcha,
        tac,
        feed-them-social