version: '2'
services:
  wordpress:
    image: minusetcortex/apsb:devel
    links:
      - db
    ports:
      - 80:80
      - 443:443
    environment:
      THEMES: pinboard
      ADMIN_EMAIL: florianchazal@gmail.com
      DB_NAME: wordpress
      DB_PASS: root
      SEARCH_REPLACE: assoc-psb.org,dev-apsb.org
      PLUGINS: >-
        akismet,
        contact-form-7,
        login-form-recaptcha,
        ml-slider,
        paypal-donations,
        really-simple-captcha,
        tac,
        tinymce-advanced,
        feed-them-social
  db:
    image: mysql:5.7 # or mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
