version: '2'
services:
  wordpress:
    image: minusetcortex/apsb:devel
    links:
      - db
    ports:
      - 80:80
      - 443:443
    environment:
      THEMES: pinboard
      ADMIN_EMAIL: florianchazal@gmail.com
      SEARCH_REPLACE: assoc-psb.org,${APSB_HOSTNAME}
      PROD_FTP_USER: ${EX2_FTP_USER}
      PROD_FTP_PASSWORD: ${EX2_FTP_PASSWORD}
      PROD_FTP_HOST: ${EX2_FTP_HOST}
      PLUGINS: >-
        akismet,
        contact-form-7,
        login-form-recaptcha,
        ml-slider,
        really-simple-captcha,
        tac,
        feed-them-social
  db:
    image: mysql:5.7 # or mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
